---
project:
  type: website
  output-dir: docs
title: "まずは使ってみる"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
format:
  html:
    toc: true
    toc-title: 目次
    toc_float: true
    toc-depth: 4
    number-sections: true
    theme: simplex
lang: ja
---

## tibble

[tibble](https://tibble.tidyverse.org/){target="_blank"}

### tidyr

[tidyr](https://tidyr.tidyverse.org/){target="_blank"}

```{r}
iris
dim(iris)
iris_long <- tidyr::pivot_longer(iris, cols = Sepal.Length:Petal.Width)
iris_long
dim(iris_long)
```

`tidyr::pivot_wider()`

`tidyr::spread()` と `tidyr::gather()` は古い関数なので，覚える必要はない。
しかし，使う人が多すぎるため，パッケージから削除できずに残っている。

ワイドはMicrosoft Excelでよく見る，複数の列がある表のようなデータ形式のことです。
一方，ロングというデータ形式もあり，列数は限られています。
ワイドは横に長く，ロングは縦に長いデータフレームです。


### dplyr

[dplyr](https://dplyr.tidyverse.org/){target="_blank"}

#### select

```{r}
iris["Species"]
iris |> dplyr::select(Species)
```

#### count

```{r}
table(iris$Species)
iris |> dplyr::count(Species)
```

#### arrange()

```{r}
iris[order(iris$Sepal.Length, decreasing = TRUE), ]
iris |>
  dplyr::arrange(dplyr::desc(Sepal.Length))
```

#### summarise()

```{r}
lapply(split(iris, iris$Species), mean)
iris |>
  dplyr::group_by(Species) |>
  dplyr::summarize(value = mean(Sepal.Length))
```

#### group_by

```{r}
unlist(lapply(split(iris, iris$Species), nrow))
iris |>
  dplyr::group_by(Species) |>
  dplyr::count(Species) |>
  dplyr::ungroup()
```

mutate()

filter()
arrange()


### readr

[readr](https://readr.tidyverse.org/)

